version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    assignees:
      - MorevM
    commit-message:
      prefix: chore
    labels: [dependencies]
    reviewers:
      - MorevM
